## Cholesky Decomposition

Cholesky Decomposition is based on the fact that a symmetric matrix can be decomposed, as in A = L * L_Transpose. 

But this method works only for positive definite matrices.

Another benefit of dealing with positive definite symmetric matrices is that pivoting is not required to avoid division by zero. 

Thus, we can implement the algorithm without the complication of pivoting.

In [1]:
#importing libraries

import numpy as np
from math import sqrt
from pprint import pprint

In [2]:
#edit the matrix below

a = (np.array([[4.0, 3.0, 2.0, 1.0], [3.0, 3.0, 2.0, 1.0], [2.0, 2.0, 2.0, 1.0], [1.0, 1.0, 1.0, 1.0]]))

b = np.array([[1],[-3],[0],[5]], float)
b1 = np.array([[1],[-3],[0],[5]], float)

pprint(a)
pprint(b)

array([[4., 3., 2., 1.],
       [3., 3., 2., 1.],
       [2., 2., 2., 1.],
       [1., 1., 1., 1.]])
array([[ 1.],
       [-3.],
       [ 0.],
       [ 5.]])


In [3]:
def cholesky(A):
    n = len(A)

    # Create zero matrix for L
    L = [[0.0] * n for  i in range(n)]

    # Perform the Cholesky decomposition
    
    for i in range(n):
        for k in range(i+1):
            tmp_sum = sum(L[i][j] * L[k][j] for j in range(k))            
            
            if (i == k): # Diagonal elements                
                L[i][k] = sqrt(A[i][i] - tmp_sum)
            else:
                L[i][k] = (1.0 / L[k][k]) * ((A[i][k] - tmp_sum))
    return L

In [4]:
def multiply(a, b):
    c = np.zeros((len(a),len(b[0])))
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(a[0])):
                c[i,j] += a[i,k]*b[k,j]
    return c

In [5]:
print(a)
L_cholesky = np.array(cholesky(a))
pprint(np.around(L_cholesky, 6))
print("\n")
print("multiplying to verify")
print("\n")
pprint(multiply(L_cholesky , L_cholesky.T))

[[4. 3. 2. 1.]
 [3. 3. 2. 1.]
 [2. 2. 2. 1.]
 [1. 1. 1. 1.]]
array([[2.      , 0.      , 0.      , 0.      ],
       [1.5     , 0.866025, 0.      , 0.      ],
       [1.      , 0.57735 , 0.816497, 0.      ],
       [0.5     , 0.288675, 0.408248, 0.707107]])


multiplying to verify


array([[4., 3., 2., 1.],
       [3., 3., 2., 1.],
       [2., 2., 2., 1.],
       [1., 1., 1., 1.]])


In [6]:
def backsub(u, b):
    n = len(u[0])
    x = np.zeros(n)
    for i in range(1,n+1):
        x[-i] = b[-i]
        for j in range(1,i):
            x[-i] -= u[-i][-j]*x[-j]
        x[-i] /= u[-i][-i]
    return x


def fwdsub(l, b):
    n = len(l[0])
    d = b
    for i in range(n):
        for j in range(i):
            d[i] -= l[i][j]*d[j]
        d[i] /= l[i][i]
    return d

In [7]:
l = cholesky(a.copy())
d = fwdsub(l, b1)
u = np.transpose(l)
x = backsub(u, d)
pprint(x)

array([ 4., -7., -2., 10.])


In [8]:
a1 = [[6.0, 15.0, 55.0], [15.0, 55.0, 225.0], [55.0, 225.0, 979.0]]

pprint(np.around(a1, 6))

L1 = cholesky(a1)

pprint(np.around(L1, 4))

array([[  6.,  15.,  55.],
       [ 15.,  55., 225.],
       [ 55., 225., 979.]])
array([[ 2.4495,  0.    ,  0.    ],
       [ 6.1237,  4.1833,  0.    ],
       [22.4537, 20.9165,  6.1101]])


In [9]:
print(np.around(np.dot(a, x).reshape(4, 1), 6))
print(b)

[[ 1.]
 [-3.]
 [ 0.]
 [ 5.]]
[[ 1.]
 [-3.]
 [ 0.]
 [ 5.]]
