# LU Decomposition

LU decomposition methods separate the time-consuming elimination of the matrix A from the manipulations of the right-hand side {B}. Thus, once A has been “decomposed,” multiple right-hand-side vectors can be evaluated in an efficient manner.

In LU decomposition, we "decompose" the matric A into a lower triangular matrix L, and an upper triangular matrix U such that LU = A.

To solve AX = B, decompose the matrix A into L and U. Solve LY = B using forward substitution and UX = Y using backward substitution.

In [37]:
#importing libraries

import numpy as np
from math import sqrt
from pprint import pprint

In [38]:
#edit the matrix below

a = (np.array([[4.0, 3.0, 2.0, 1.0], [3.0, 3.0, 2.0, 1.0], [2.0, 2.0, 2.0, 1.0], [1.0, 1.0, 1.0, 1.0]]))

b = np.array([[1],[-3],[0],[5]], float)
b1 = np.array([[1],[-3],[0],[5]], float)

pprint(a)
pprint(b)

array([[4., 3., 2., 1.],
       [3., 3., 2., 1.],
       [2., 2., 2., 1.],
       [1., 1., 1., 1.]])
array([[ 1.],
       [-3.],
       [ 0.],
       [ 5.]])


In [39]:
#implementation of a simple LU factorization

def lu(A):
    
    #Get the number of rows
    n = len(A[0])
    
    U = A.copy()
    L = np.eye(n)
    
    #Loop over rows
    for i in range(n):
        for j in range(i + 1, n):
            factor = (U[j][i]/U[i][i])
            L[j][i] = factor
            U[j] -= (factor) * (U[i])
        
    return L, U    


In [40]:
def multiply(a, b):
    c = np.zeros((len(a),len(b[0])))
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(a[0])):
                c[i,j] += a[i,k]*b[k,j]
    return c

In [33]:
L, U = lu(a)

pprint(a)

print("\nLower Matrix \n")
pprint(np.around(L, 6))
print("\nUpper Matrix \n")
pprint(np.around(U, 6))

print("\nMultiplying to verify\n")
pprint(multiply(L, U))

array([[4., 3., 2., 1.],
       [3., 3., 2., 1.],
       [2., 2., 2., 1.],
       [1., 1., 1., 1.]])

Lower Matrix 

array([[1.      , 0.      , 0.      , 0.      ],
       [0.75    , 1.      , 0.      , 0.      ],
       [0.5     , 0.666667, 1.      , 0.      ],
       [0.25    , 0.333333, 0.5     , 1.      ]])

Upper Matrix 

array([[4.      , 3.      , 2.      , 1.      ],
       [0.      , 0.75    , 0.5     , 0.25    ],
       [0.      , 0.      , 0.666667, 0.333333],
       [0.      , 0.      , 0.      , 0.5     ]])

Multiplying to verify

array([[4., 3., 2., 1.],
       [3., 3., 2., 1.],
       [2., 2., 2., 1.],
       [1., 1., 1., 1.]])


In [34]:
def fwdsub(l, b):
    n = len(l[0])
    d = b
    for i in range(n):
        for j in range(i):
            d[i] -= l[i][j]*d[j]
        d[i] /= l[i][i]
    return d

In [35]:
def backsub(u, b):
    n = len(u[0])
    x = np.zeros(n)
    for i in range(1,n+1):
        x[-i] = b[-i]
        for j in range(1,i):
            x[-i] -= u[-i,-j]*x[-j]
        x[-i] /= u[-i,-i]
    return x


In [36]:
d = fwdsub(L, b1)

x = backsub(U, d)

print(x)


[ 4. -7. -2. 10.]


In [44]:
np.around((np.dot(a, x)).reshape(4,1), 6)

array([[ 1.],
       [-3.],
       [-0.],
       [ 5.]])

In [41]:
a2 = np.array([[3, -0.1, -0.2], [0.1, 7, -0.3], [0.3, -0.2, 10]], float)
print(a2)
L2, U2 = lu(a2)
pprint(L2)
pprint(U2)
pprint(multiply(L2, U2))

[[ 3.  -0.1 -0.2]
 [ 0.1  7.  -0.3]
 [ 0.3 -0.2 10. ]]
array([[ 1.        ,  0.        ,  0.        ],
       [ 0.03333333,  1.        ,  0.        ],
       [ 0.1       , -0.02712994,  1.        ]])
array([[ 3.        , -0.1       , -0.2       ],
       [ 0.        ,  7.00333333, -0.29333333],
       [ 0.        ,  0.        , 10.01204188]])
array([[ 3. , -0.1, -0.2],
       [ 0.1,  7. , -0.3],
       [ 0.3, -0.2, 10. ]])
